---
- name: "Clone a virtual machine from template and customize"
  hosts: all

  # Setup these variables to match your VM environment.
  vars:
    vcenter_server: 
    vcenter_user: 
    vcenter_pass: 
    datacenter_name: 
    # This is hostname of particular ESXi server and/or cluster on which user wants VM to be deployed
    cluster_name:
    # esxi_hostname:
    # VM configs
    vm_networks: 
    vm_name: 
    vm_folder:
    datacenter_name:
    vm_template:
    vm_datastore:    
    vm_num_cpus:
    vm_memory:
    
    
    
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_name }}"
      template: "{{ vm_template }}"
      datacenter: "{{ datacenter_name }}"
      folder: /LAB_Datacenter/Apps/AutoDeploy
      cluster: "{{ cluster_name }}"
      datastore: " DS_SSD0 " 
      hardware: 
        num_cpus: "{{ vm_num_cpus }}"
        memory_mb: "{{ vm_memory }}" 
      networks:  
      - name: "{{ vm_networks }}"
        # ip: 
        # netmask:  
        # gateway:  
        # type: static
        # dns_servers: 
      # customization:
        # hostname: "{{ vm_name }}"
        # dns_servers:        
      # state: poweredon
      # wait_for_ip_address: yes
    # delegate_to: localhost