---
- name:  Clone a virtual machine from template and customize
  - hosts: 
  gather_facts: no
  vars:
    vcenter_server: 
    vcenter_user: 
    vcenter_pass: 
    datacenter_name: 
    # This is hostname of particular ESXi server and/or cluster on which user wants VM to be deployed
    cluster_name:
    #esxi_hostname:
    #VM configs
    vm_networks: 
    vm_name: 
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_name }}"
      template: 
      datacenter: "{{ datacenter_name }}"
      folder: 
      cluster: "{{ cluster_name }}"
      datastore:  
      hardware: 
        num_cpus:
        memory_mb:  
      networks: "{{ vm_networks }}" 
      #- name: 
        #ip: 
        #netmask:  
        #gateway:  
        #type: static
        #dns_servers: 
      #customization:
        #hostname: "{{ vm_name }}"
        #dns_servers:        
      state: poweredon
      #wait_for_ip_address: yes
    delegate_to: localhost